# Generated by Django 3.1.4 on 2021-02-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cardamage',
            name='d_type',
        ),
        migrations.AddField(
            model_name='cardamage',
            name='damage_type',
            field=models.ManyToManyField(to='car_rental_app.DamageType'),
        ),
    ]
