# Generated by Django 3.1.4 on 2021-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0002_auto_20210216_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientask',
            name='car',
        ),
        migrations.AddField(
            model_name='clientask',
            name='car_class',
            field=models.CharField(choices=[('premium', 'Premium'), ('hatchback', 'Hatchback'), ('city_cars', 'Small Car'), ('mpv', 'MPV'), ('van', 'Cargo Van')], default=None, max_length=32, verbose_name='Car class'),
        ),
    ]
