# Generated by Django 3.1.6 on 2021-02-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental_app', '0004_auto_20210225_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DamageType',
            new_name='DamagePart',
        ),
        migrations.RenameField(
            model_name='damagepart',
            old_name='name',
            new_name='part',
        ),
        migrations.RemoveField(
            model_name='cardamage',
            name='damage_type',
        ),
        migrations.AddField(
            model_name='cardamage',
            name='damage_part',
            field=models.ManyToManyField(to='car_rental_app.DamagePart'),
        ),
    ]
